### ISSUE TITLE
Wrong operation order

### ISSUE THREAD

**Issue by Daguerreo** [berendeanicolae/ColorSpace#2]
https://github.com/berendeanicolae/ColorSpace/blob/478ebfed728c7989ab17d0fa03a9095abca9530d/src/Conversion.cpp#L112

2 * 1 -  temp 

Always evaluate 2*1 first, if not intended is 2 * (1-temp)

**Comment by berendeanicolae** [comment]
First of all, the code is:
`temp1 = 2 * l - temp2; // temp1 = 2*lightness - temp2`
I've checked other references I've found and they have the same algorithm to convert from hsl to rgb.
To be honest, I remember that not all the tests passed, but the precision was good enough for what I used the project for.
If you have any other suggestions, create a pull request and I will look over it.
